name: Setup Simba
description: Download and setup Simba
author: Torwent
branding:
  icon: flag
  color: green

inputs:
  setup-srl:
    description: Wether to setup SRL or not
    required: false
  setup-wasplib: # id of input
    description: Wether to setup SRL or not
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Simba
      run: |
        mkdir ./Simba
        curl --retry 5 -L -o ./Simba/Simba.exe https://github.com/ollydev/Simba/releases/download/simba1400-lape-update/Simba-Win32.exe
        mkdir ./Simba/Includes/
        mkdir ./Simba/Scripts/
      shell: bash

    - name: Setup SRL
      if: ${{ inputs.setup-srl == 'true' }}
      run: |
        cd ./Simba/Includes/
        git clone https://github.com/ollydev/SRL.git
      shell: bash

    - name: Setup WaspLib
      if: ${{ inputs.setup-wasplib == 'true' }}
      run: |
        cd ./Simba/Includes/
        git clone https://github.com/Torwent/WaspLib.git
      shell: bash
